apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus-server
spec:
  capacity:
    storage: 1Gi  # Adjust size as needed
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual  # This should match the PVC storage class
  hostPath:
    path: "/mnt/data/prometheus-server"  # Adjust path as needed

