apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus-alertmanager
spec:
  serviceName: "alertmanager"
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: quay.io/prometheus/alertmanager:v0.27.0
        ports:
        - containerPort: 9093
        volumeMounts:
        - name: storage
          mountPath: /alertmanager
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
      storageClassName: manual  # Specify the desired storage class

